### get data Produk`
GET http://localhost:3000/api/semuaProduk?id=all

### get data Produk` by id
GET http://localhost:3000/api/semuaProduk?id=Nu_27_Un_Or_Pe_1692805428660_1693804003093

### get data Produk` by id
GET http://localhost:3000/api/orderan/Ta_42_Un_Or_Pe_1692805239752_1692850670597


### create data Produk`
POST http://localhost:3000/api/semuaProduk
Content-Type: application/json

{
  "id": "Ta_50_Un_Or_Pe_1692805286012_169286063212",
  "nama": "kosong",
  "lokasi": "kosong",
  "jenis": "kosong",
  "harga": 0,
  "jumlah": 0,
  "img": "kosong",
  "keterangan": "kosong",
  "orderanId": "petri_biki_230909_Sem_22222"
}


### update data Produk`
PUT http://localhost:3000/api/semuaProduk/tambah produk 1
Content-Type: application/json

{
  "id": "Ta_50_Un_Or_Pe_1692805286012_1692860638296",
  "nama": "Tahu Bakso Specialty",
  "lokasi": "Ungaran",
  "jenis": "Orderan",
  "harga": 50000,
  "jumlah": 1,
  "img": "/img/produk/1692805286010_Tahu Bakso Specialty.png",
  "keterangan": "Pedas",
  "created_at": "2023-07-24T07:03:58.000Z",
  "updated_at": "2023-08-24T07:03:58.299Z",
  "orderanId": "Orang_Semb_250928_Sem_98797"
}

### delete data Produk`
DELETE http://localhost:3000/api/semuaProduk/tambah produk 1
