### get data Form
GET http://localhost:3000/api/delivery
Content-Type: application/json


### get data Form by id
GET http://localhost:3000/api/delivery/1
Content-Type: application/json

{
}

### create data Form
POST http://localhost:3000/api/delivery/
Content-Type: application/json

{
  "nama": "kosong",
  "hp": "kosong",
  "lokasi": "kosong",
  "jenis": "kosong",
  "harga": 0,
  "img": "kosong",
  "keterangan": "kosong"
}


### create data Form Text Only
PUT http://localhost:3000/api/delivery/1
Content-Type: application/json

{
  "nama": "kosong update",
  "hp": "kosong",
  "lokasi": "kosong",
  "jenis": "kosong",
  "harga": 0,
  "img": "kosong",
  "keterangan": "kosong"
}



### delete data Form
DELETE http://localhost:3000/api/delivery/1
Content-Type: application/json

{
}
