@api = http://localhost:3000/api
@path = {{api}}/product
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsIm5hbWUiOiJ1c2VyMyIsImlkIjoiY20wbWV2anpoMDAwODE3Znp6bXB2NmN2YiIsImlhdCI6MTcyNTM2Njg1MiwiZXhwIjoxNzI1MzcwNDUyfQ.kl9fsKOxorSz58NuT5EdozySddWFML24rMIJhqAvNUs

### get data Produk
GET {{path}}

### get data Produk with param
GET {{path}}?page=100&take=2
Authorization: Bearer {{token}}

### get data Produk by id
GET {{path}}/1
Authorization: Bearer {{token}}

### create data Produk`
POST  {{path}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "harga": 20000,
  "img": "tidak ada ",
  "jenis": "orderan",
  "jumlah": 86,
  "keterangan": "Pedas",
  "lokasi": "Semarang",
  "nama": "tahu baxo enak sekali"
}


### update data Produk`
PUT {{path}}/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nama": "tahu baxo update",
  "harga": 20000,
  "img": "tidak ada ",
  "jenis": "orderan",
  "jumlah": 1,
  "keterangan": "Pedas",
  "lokasi": "Semarang"
}


### delete data Produks`
DELETE {{path}}/1
Authorization: Bearer {{token}}
