@api = http://localhost:3000/api
@path = {{api}}/user
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIzQGdtYWlsLmNvbSIsIm5hbWUiOiJ1c2VyMyIsImlkIjoiY20wbWV2anpoMDAwODE3Znp6bXB2NmN2YiIsImlhdCI6MTcyNTM2Njg1MiwiZXhwIjoxNzI1MzcwNDUyfQ.kl9fsKOxorSz58NuT5EdozySddWFML24rMIJhqAvNUs

###
POST {{path}}/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "user1234"
}

###
POST {{path}}/register
Content-Type: application/json

{
  "fullname": "user3",
  "email": "user3@gmail.com",
  "password": "user1234",
  "confPass": "user1234",
  "phone": "081 1232 1234",
  "address": "jln jakarta raya"
}

###
GET {{path}}/refresh
Content-Type: application/json

###

DELETE {{path}}/logout
Content-Type: application/json
Authorization: "Bearer {{token}}"

###
GET {{path}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
