### get all data Orderan
GET http://localhost:3000/api/orderan?option=orderan
Content-Type: application/json


### get all
GET http://localhost:3000/api/orderan?id=all&table=table
Content-Type: application/json

### get by id
GET http://localhost:3000/api/orderan?id=1_231



### post
POST http://localhost:3000/api/orderan
Content-Type: application/json

{
  "dari": "tokopedia ku lagi 23",
  "pengirim": "kosong",
  "hpPengirim": "123",
  "penerima": "kosong",
  "alamatPenerima": "kosong",
  "hpPenerima": "12",
  "pesan": "2023-12-12T00:00:00.000Z",
  "waktuKirim": "2023-12-12T00:00:00.000Z",
  "guna": "kosong",
  "lokasi": "kosong",
  "namaPengiriman": "kosong",
  "ongkir": 0,
  "typePembayaran": "kosong",
  "totalBayar": 0,
  "totalPenjualan": 0,
  "status": "Kirim",
  "semuaProduct": [
    {
      "harga": 3681802,
      "jenis": "string",
      "jumlah": 10,
      "lokasi": "string",
      "nama": "string",
      "img": "dasda"
    }
  ]
}

### Update
PUT http://localhost:3000/api/orderan?id=Piuvr_L_231221_Sem_02817
Content-Type: application/json

{
  "dari": "tokopedia update",
  "pengirim": "kosong",
  "hpPengirim": "123",
  "penerima": "kosong",
  "alamatPenerima": "kosong",
  "hpPenerima": "12",
  "pesan": "2023-12-12T00:00:00.000Z",
  "waktuKirim": "2023-12-12T00:00:00.000Z",
  "guna": "kosong",
  "lokasi": "kosong",
  "namaPengiriman": "kosong",
  "ongkir": 0,
  "typePembayaran": "kosong",
  "totalBayar": 0,
  "totalPenjualan": 0,
  "status": "Kirim",
  "semuaProduct": [
    {
      "harga": 3681802,
      "jenis": "string",
      "jumlah": 10,
      "lokasi": "string",
      "nama": "string",
      "img": "dasda"
    }
  ]
}


### Update
PUT http://localhost:3000/api/orderan/Lam b_327_Ot_240229_1312_Sem_32746412
Content-Type: application/json

{
  "alamatPenerima": "Alamat Penerima",
  "guna": "Keterangan update",
  "hpPenerima": "Hp Penerima update",
  "hpPengirim": "Hp Pengirim update",
  "id": "Lam b_327_Ot_240229_1312_Sem_32746412",
  "lokasi": "Lokasi update",
  "namaPengiriman": "Nama Form update",
  "ongkir": 23,
  "penerima": "Penerima update update",
  "pengirim": "orang genah update",
  "pesan": "2023-07-04",
  "semuaHargaItem": 12312,
  "semuaHargaOrderan": 12312,
  "semuaHargaProduct": 12312,
  "status": "Status",
  "totalBayar": 123,
  "totalHarga": 1231,
  "totalPenjualan": 232,
  "typePembayaran": "Pemsbayaran",
  "kirim": "2023-07-04",
  "waktuKirim": "2023-07-20T00:00:00.000Z",
  "semuaProduct": [
    {
      "harga": 42000,
      "id": "produk lagi1 asd",
      "jumlah": 10,
      "jenis": "Itesm",
      "keterangan": "Esnak",
      "lokasi": "Ungsaran",
      "nama": "Tahu sBakso Rebus",
      "orderanId": "Lam b_327_Ot_240229_1312_Sem_32746412"
    },
    {
      "harga": 42000,
      "id": "produk lagi asd",
      "jumlah": 10,
      "jenis": "Itesm",
      "keterangan": "Esnak",
      "lokasi": "Ungsaran",
      "nama": "Tahu sBakso Rebus",
      "orderanId": "Lam b_327_Ot_240229_1312_Sem_32746412"
    }
  ]
}


### delete
DELETE http://localhost:3000/api/orderan?id=1_231
Content-Type: application/json

{}

####
POST http://localhost:3000/api/orderan
Content-Type: application/json

{
  "alamatPenerima": "Alamat Penerima",
  "ongkir": 23,
  "id": "Lam5b_327_Ot_240229_1312_Sem_327464sd",
  "no": "1",
  "semuaHargaItem": 12312,
  "semuaHargaOrderan": 12312,
  "semuaHargaProduct": 12312,
  "lokasi": "Lokasi update",
  "ekspedisi": "Ekspedisi update",
  "guna": "Keterangan update",
  "hpPenerima": "Hp Penerima update",
  "hpPengirim": "Hp Pengirim update",
  "namaPengiriman": "Nama Form update",
  "pengirim": "orang genah update",
  "penerima": "Penerima update update",
  "kirim": "1999-07-01",
  "pesan": "2000-07-01",
  "semuaProduct": [
    {
      "harga": 42000,
      "id": "1",
      "jumlah": 10,
      "jenis": "Itesm",
      "keterangan": "Esnak",
      "lokasi": "ungaran",
      "img": "kosong",
      "nama": "Tahu sBakso Rebus",
      "orderanId": "Lam5b_327_Ot_240229_1312_Sem_327464sd"
    },
    {
      "harga": 42000,
      "id": "2",
      "jumlah": 10,
      "jenis": "Itesm",
      "keterangan": "Enak",
      "lokasi": "ungaran",
      "nama": "Tahu sBakso Rebus",
      "img": "kosong",
      "orderanId": "Lam5b_327_Ot_240229_1312_Sem_327464sd"
    }
  ],
  "status": "Status",
  "total": 123,
  "totalBayar": 123,
  "totalHarga": 1231,
  "totalPenjualan": 232,
  "typePembayaran": "Pemsbayaran",
  "waktuKirim": "03:00:00"
}

###
GET http://localhost:3000/api/orderan/table/