import type { Metadata } from 'next'
import { Inter, Nunito } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const nunito = Nunito({
	subsets : ['latin'],
	weight : ['400', '700']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html
			lang='en'
			className={nunito.className}
			// data-theme={ 'mytheme' }
		>
			<body className={'  min-h-screen '}>
			<div className='container '>
					{ children}
				</div>
			</body>
		</html>
	)
}
